### ISSUE TITLE
bug/I could not enter my process.

### ISSUE THREAD

**Issue by leeduckgo** [permaweb/ao#1081]
The process id:

> cO4thcoxO57AflN5hfXjce0_DydbMJclTU9kC3S75cg

<img width="717" alt="image" src="https://github.com/user-attachments/assets/2439287d-9e6d-450a-8724-f2fc87f399af">

**Comment by twilson63** [comment]
Checking it out now, also check your VPN connections and see the help section in the AO Discord

**Comment by leeduckgo** [comment]
> Checking it out now, also check your VPN connections and see the help section in the AO Discord

<img width="665" alt="image" src="https://github.com/user-attachments/assets/b1d19acc-233f-45d6-a54e-6d2f7f1659b0">

Keep pending with the computing...

I tried the other processes and the others are working, I created a ticket in the AO Discord:
> #ticket-0021

**Comment by twilson63** [comment]
Just rechecked it is still cycling through previous messages, hopefully it will catch up shortly, I will keep an eye on it

**Comment by leeduckgo** [comment]
> Just rechecked it is still cycling through previous messages, hopefully it will catch up shortly, I will keep an eye on it

thx~thx~

**Comment by leeduckgo** [comment]
> Just rechecked it is still cycling through previous messages, hopefully it will catch up shortly, I will keep an eye on it

recognized that there are some msgs are stuck for a long time:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/f911bbac-e51e-4715-94b3-5704ed5ca2e5">

What could I do for this situation🤔🤔?

**Comment by twilson63** [comment]
it just seem to be processing a bunch of error messages
 can you share the source code?

What is the purpose of this process?
