### ISSUE TITLE
scheduler-utils: trim trailing slash from `Url` if it exists

### ISSUE THREAD

**Issue by TillaTheHun0** [permaweb/ao#246]
so `Url` is a consistent shape that can be safely appended to

**Comment by Merdi-kim** [comment]
Just checking to see if this still needs to be worked on

**Comment by TillaTheHun0** [comment]
@Merdi-kim yep, it is available.

**Comment by Merdi-kim** [comment]
alright, lemme work on it

**Comment by jrdn91** [comment]
I will pick this up
