### ISSUE TITLE
Running CU on Linux Issues

### ISSUE THREAD

**Issue by zyjblockchain** [permaweb/ao#520]
When I try to run cu on ubuntu, but when I  use npm i and get those error:
<img width="944" alt="image" src="https://github.com/permaweb/ao/assets/40423181/0c3aa1a2-ab5a-4946-a038-ec97c0e8e4b5">

**Comment by twilson63** [comment]
do you have build-essentials installed?

sudo apt-get update
sudo apt-get install build-essential

**Comment by TillaTheHun0** [comment]
@zyjblockchain `heapdump` requires native bindings and it looks like you're missing some tooling on the host required for that, specifically `make` as indicated by the stack trace. I'd suggest following @twilson63 advice

**Comment by MichaelBuhler** [comment]
@zyjblockchain Let us know if the `build-essential` package doesn't work for you.
