### ISSUE TITLE
Compatibility with bun

### ISSUE THREAD

**Issue by elliotsayes** [permaweb/ao#533]
Issue when running code via `bun file.ts` but not via `bunx tsx file.ts`:

<img width="843" alt="Screenshot 2024-03-12 at 4 51 55 PM" src="https://github.com/permaweb/ao/assets/7699058/a7e3a9c1-d529-4601-93d8-09e5993a028e">

`ao.ts`:
```ts
import { createDataItemSigner, message } from "@permaweb/aoconnect";
import * as fs from "node:fs";

const wallet = JSON.parse(
  fs.readFileSync("./.secret/ao_test_key.json", "utf8")
);

const signer = createDataItemSigner(wallet);

const processId = "Jx8okHiQGNgy-TrJR85K8S2DpO3-Uanh2FFOzW-tMzE";
const data = "Hello, from aoconnect!";
const messageId = await message({
  process: processId,
  signer,
  // anchor,
  // tags,
  data,
});
console.log({ messageId });
```

**Comment by rosmcmahon** [comment]
likely an issue with bun's crypto sign function.
see this issue in arweave-js also: https://github.com/ArweaveTeam/arweave-js/issues/223

**Comment by TillaTheHun0** [comment]
Closing, as it seems to be a known issue with Bun crypto compat. If it ends being something on our end, we can reopen

**Comment by kay-is** [comment]
@TillaTheHun0 

I got it working by using the `./dist/browser.js` in Bun.

Bun supports Web Crypto, which doesn't seem to have the compat issues from their node:crypto module.

It seems these are the exports that Bun can use:

```
"exports": {
    "bun": "./index.js",
    "worker": "./index.js",
    "node": "./index.js",
    "require": "./index.js", // if importer is CommonJS
    "import": "./index.mjs", // if importer is ES module
    "default": "./index.js",
}
```

So, in theory it should be possible to tell Bun to use the browser.js, which, in turn uses Web Crypto.
