### ISSUE TITLE
Make the testnet Accessible for public 

### ISSUE THREAD

**Issue by Freedomfightersng** [permaweb/ao#561]
Kindly make this testnet available for degens like me to tinker with. Please.

**Comment by TillaTheHun0** [comment]
Hey, thanks for the issue. The ao testnet is available to developers to start tinkering. You can find more information on how to get started in the [ao Cookbook](https://cookbook_ao.arweave.dev/welcome/index.html).

You can also ask questions in the [ao Discord](https://discord.gg/vYctEs7aTd).

Thanks for checking it out, and happy building!
