### ISSUE TITLE
feat (CU): Msg.From? via a Dry Run

### ISSUE THREAD

**Issue by twilson63** [permaweb/ao#617]
If `From-Process` tag is set in a dry run, we should set the From tag to be that process, and if not, we should set the Owner tag.

Any issues with adding this feature?

**Comment by TillaTheHun0** [comment]
[Dry Run already does this in the CU](https://github.com/permaweb/ao/blob/fa73b15294338b3a42c848cf6c3c41320ad977af/servers/cu/src/domain/api/dryRun.js#L143).

**Comment by TillaTheHun0** [comment]
The CU already does this, so closing. If it's not working, then comment back here, and we can re-open
