### ISSUE TITLE
build(su): su.yml that was added is crashing the testing CI

### ISSUE THREAD

**Issue by VinceJuliano** [permaweb/ao#683]
## Background

A su.yml file was added in a previous PR that uses a docker image we dont have access to

## Problem

This is causing the SU testing CI to record a failure

## Solution

Fix or remove this .yml file

## Developer Notes

We will have to make the docker image publicly accessible or modify the .yml

**Comment by dtfiedler** [comment]
Related fix - https://github.com/permaweb/ao/pull/879
