### ISSUE TITLE
bug(MU-Router): can not post assign to mu

### ISSUE THREAD

**Issue by twilson63** [permaweb/ao#726]
# Background

clients should be able to post the mu.ao-testnet.xyz and it should perform the assignment correctly.

`POST {MU}/?process-id={id}&assign={tx}`

# Problem

When trying to post an existing tx to a process via the mu router I get an error

https://hopp.sh/r/g5zMVjJQPFMZ

**Comment by TillaTheHun0** [comment]
This should be fixed when 0de056467a7668d808610c6d7e9ca266d9c7302d is live
