### ISSUE TITLE
(mu): Message with a number as a tag value causes error

### ISSUE THREAD

**Issue by keikari** [permaweb/ao#777]
This created a message with one of its tag values being a number. And the message didn't got in to Arweave.
https://cu.ao-testnet.xyz/result/aQwOzUrY1CKj10bKMWd5QxZ8yPdho_RQ5D1uwKJ5jvA?process-id=-miqWPZckoyTqX0P67YV5-t9yDjBWjsj8gGXV0g8rA0

Screenshot from MU
![2024-06-06_19-41](https://github.com/permaweb/ao/assets/34790748/d8dd4317-49eb-4b8a-a738-ad87bfd16a38)

**Comment by twilson63** [comment]
All Tag Values must be strings you have use the `tostring` function to
convert the value to a string.
