### ISSUE TITLE
[dev-cli::emcc-lua] Process.js is removed, which behaviour is different from the description in the document

### ISSUE THREAD

**Issue by RyanKung** [permaweb/ao#794]
In emcc-lua, the `process.js` is removed after emcc compile

https://github.com/permaweb/ao/blob/9b7eefd9e15aaf1f6b12a98e20daf9a45638c3a1/dev-cli/container/src/emcc-lua#L200

Which  is different from what is described in the document

https://github.com/permaweb/ao/tree/main/dev-cli#testing-example

```md
Testing example
Once you have built your Lua into Wasm using ao build, the output will be a process.js and a process.wasm file.

The process.js file is the JS interop that allows invoking Wasm from a JS program, while the process.wasm is your Lua code compiled into Wasm.
```

**Comment by TillaTheHun0** [comment]
Thanks for reporting. We'll get the README updated.

**Comment by jrdn91** [comment]
Working on this
