### ISSUE TITLE
perf(mu): Implement Application metrics to indicate application health

### ISSUE THREAD

**Issue by TillaTheHun0** [permaweb/ao#801]
```
As a MU operator
I would like specific metrics exposed on my OpenTelemetry endpoint
So that I can peer into the health of my unit and diagnose issues
```

## Acceptance Criteria

- [x] #802

```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the http request total count and quantiles for the following endpoints:
- /monitor/:processId
- /
```

> This most likely is best implemented as a Histogram _and/or_ Summary

- [x] #826
```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the number of requests being made to external sources and their respective response times. External sources include:

- Gateway
- CU
- SU
- etc.
```

> This most likely is best implemented as a Histogram _and/or_ Summary

- [x] #830
```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the number of Data Items in the Push Queue
```

> This most likely is best implemented as a Gauge. If using worker threads, push queues will need to be aggregated across workers

- [ ] #865

```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the amount of time each Data Item's "chain" of pushes take to be pushed through the network
```

- [ ] #866

```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the length of "push chains" being pushed by the MU
```

> For example, a message, whose result contains a message to be pushed, whose result contains a message to be pushed, whose result contains nothing to be pushed would have a "push length" of `3`

- [x] #856

```
GIVEN I am a MU operator
WHEN I send a GET to the /metrics endpoint
THEN I should receive OpenMetrics detailing the number of Cron Monitors currently running
```

> This most likely is best implemented as a Gauge. If using worker threads, push queues will need to be aggregated across workers

## Developer Notes

Metrics may be broken into sub issues as needed.

**Comment by jrdn91** [comment]
Breaking out the two remaining tasks here into new issues #865 and #866 as they are quite a bit more complicated and will require a bit of potential retooling of the worker and queue system to better accommodate push queue related metrics.
