### ISSUE TITLE
test(cu): implement tests for `saveCheckpointWith`

### ISSUE THREAD

**Issue by TillaTheHun0** [permaweb/ao#804]
## Background

`ao-process.js` in the CU contains side effects pertaining to ao processes. One of these is `saveCheckpointWith`, which contains the logic for querying, building, signing, and uploading ao Process `Checkpoints` to Arweave, as well as caching them as a record in the SQLite DB (see #776)

## Problem

This api currently lacks unit tests asserting it's correctness

## Solution

Write the tests :)

**Comment by jrdn91** [comment]
I will start working through this one.
