### ISSUE TITLE
New messages created as a result to a process `Spawned` success message don't seem to get cranked to Arweave

### ISSUE THREAD

**Issue by keikari** [permaweb/ao#847]
Steps to see the issue:
1. Start a new process in Aos
2. Add this handler to it:
```
Handlers.add('Spawned', Handlers.utils.hasMatchingTag('Action', 'Spawned'), function()
    ao.send({
	Target = ao.id,
	Data = "hi",
    });
end)
```
3. Spawn a new process 
```
Spawn("Pq2Zftrqut0hdisH_MC2pDOT6S4eQFoxGsFUzR6r350")
```

4. When the process receives `Spawned` success message and handles it, the new message created in the handler is seemingly just dropped, and doesn't make it to Arweave. 

For example, a message caused by this `Spawned` action `glzbf4a20KavGXAopeRBO4wGHQangUg-fU2BP6M-afs` can't be found from Arweave.
Result:
https://cu.ao-testnet.xyz/result/glzbf4a20KavGXAopeRBO4wGHQangUg-fU2BP6M-afs?process-id=geHYL5ORxPtnjGf7FSH0bJu2rGJZBxuSRmOcizYFaSg

**Comment by samcamwilliams** [comment]
Thanks for reporting! I will flag to the team and we will take a look.

CC @VinceJuliano @TillaTheHun0

**Comment by TillaTheHun0** [comment]
Thanks for reporting. Interesting. So the MU builds, signs, and sends this `Spawned` message to the parent process, but I don't believe the MU then retrieves that message's result from a CU. Ergo, any outgoing messages as a result of that `Spawned` message's evaluation, would not be pushed.

I think the MU would need to enqueue an action to read the result of this `Spawned` message and push its results, just like any other message, as part of it's internal pushing mechanism.

@VinceJuliano please keep me honest.

**Comment by jfrain99** [comment]
Thank you for the issue @keikari!
