### ISSUE TITLE
Question about how to support metamask addresses and natively support 0x addresses inside ao process messages

### ISSUE THREAD

**Issue by zyjblockchain** [permaweb/ao#859]
The arbundle library is now supported on ao, meaning that multiple signature algorithms are supported, such as ecdsa.
However, when a bundle item signed with metamask is sent to ao, the message.From is not a 0x address, but a sha256 address for public, which is still generated in the same way as an arweave address, which makes it impossible for users to query the ao network for their own message with a 0x address transaction

**Comment by TillaTheHun0** [comment]
I believe this is implemented in #863  , so I am going to close this.

Please let me know if I am mistaken and I can open back up.
