### ISSUE TITLE
 feat(dev container): give developers a ready to go (customizable) dev environment

### ISSUE THREAD

**Issue by PeterFarber** [permaweb/ao#869]
## Background

Currently, developers all have there own local dev environment and/or are using [gitpod](https://www.gitpod.io/).

## Problem

- It is very difficult to setup a development environment that allows developers to spin up locally hosted versions of the AO services.
- Developers can be running different versions of Node, Rust, DENO, Lua, EMSDK.
- Developers can be using different Operating Systems: Mac, Linux, Windows ( And Subsets Of ).
- No easy way to spin up the **AO** services like the **SU**, **MU**, and **CU** and debug them locally.

## Solution

The Developer can run an development environment in docker with a predetermined configuration using [VS Code Dev Containers](https://code.visualstudio.com/docs/devcontainers/containers).

The Developer needs to install one [extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) in VS Code which gives them the ability to **open the repo in a remote container**.

**Comment by dtfiedler** [comment]
Hey @PeterFarber - have you checked out https://github.com/permaweb/ao-localnet? It containerizes the services allowing you to remote them locally.

**Comment by PeterFarber** [comment]
> Hey @PeterFarber - have you checked out https://github.com/permaweb/ao-localnet? It containerizes the services allowing you to remote them locally.

Hey @dtfiedler, Yes I have!
This works similarly but also sets up a development environment in docker with the necessary tools to develop out of the box. Also soon I plan on configuring gitpod to use it as well so devs can work in a uniform environment, without any local dependencies.
