### ISSUE TITLE
Use an exponential backoff on SU failed data item uploads

### ISSUE THREAD

**Issue by arielmelendez** [permaweb/ao#890]
The code in question:
https://github.com/permaweb/ao/blob/main/servers/su/src/domain/clients/uploader.rs#L75-L90

Retrying a failing request 100 times in 1 second intervals can be a harmful pattern for connecting with external services. At the scale that AO SUs operate, this behavior can cause substantial heartburn for downstream services. It would be great if an exponential backoff pattern could be used here. Thanks!

**Comment by ppedziwiatr** [comment]
I would also consider adding some jitter here :) Also I believe the ultimate solution is to move the dataItems delivery to a separate/background job (https://github.com/permaweb/ao/issues/877)

**Comment by VinceJuliano** [comment]
In uploader.rs, add exponential backoff to the loop that retries the upload, if it reaches some specified number of retries, say 10, add it to a persistent queue of items that need to be tried again later. And have a background process pulling from this queue and uploading.
