### ISSUE TITLE
bug(su): no longer able to run the su service in docker

### ISSUE THREAD

**Issue by dtfiedler** [permaweb/ao#932]
The changes made for https://github.com/permaweb/ao/issues/718 (commit https://github.com/permaweb/ao/commit/2edf59e9a9332f8da3f1f5442a90e3d1353ffcd5) break the ability to run the su in the docker container.

Steps to reproduce:
```bash
❯ cd servers/su
❯ docker build . -t ao-su
❯ docker run ao-su
exec /app/su: no such file or directory
```

**Comment by dtfiedler** [comment]
Fix in https://github.com/permaweb/ao/pull/933

**Comment by VinceJuliano** [comment]
Thank you, merged!
