### ISSUE TITLE
feat(dev-cli): Ability to build 32bit and 64bit modules.

### ISSUE THREAD

**Issue by PeterFarber** [permaweb/ao#958]
#### Description
I would like the ability to build both 32-bit and 64-bit WebAssembly (WASM) modules using the `ao dev-cli`. This could be implemented by adding an option in the `config.yml` file to specify whether to build 32-bit or 64-bit WASM modules.

#### Proposed Solution
- Extend the `config.yml` file to include a new option to define the target architecture (32-bit or 64-bit).
- Update the build process in `ao dev-cli` to check the configuration and compile the WASM modules accordingly.

#### Example Configuration
```yaml
# config.yml
target: 64 # Possible values: "32", "64"
```

### Benefits
- Flexibility to choose the appropriate architecture based on the target environment.
- Simplifies the build process for projects requiring specific WASM module architectures.

### Additional Context
This feature would be beneficial for developers targeting different environments, ensuring compatibility and optimal performance for both 32-bit and 64-bit systems.

### Acceptance Criteria
- The `config.yml` file accepts and correctly interprets the new `target` option.
- The `ao dev-cli` builds the WASM modules based on the specified architecture.
- Documentation is updated to reflect this new option.

**Comment by ppedziwiatr** [comment]
would you also consider adding asyncify as an option? I believe most of the processes do not need async..

**Comment by PeterFarber** [comment]
We could but I think we might also have to add another ao-loader option as well though if we did

**Comment by twilson63** [comment]
Currently, by default all processes need asyncify b/c of aolib, but we are
looking to improve this
